selectedMonth feature
aquintiliano/fifa-champs pull request #109
Opened 2018-01-21 03:56 UTC by kiosia

The long awaited feature of CREATING FINALS FOR A DIFFERENT MONTH THAN THE CURRENT ONE!!111eleven!!

Now the matches are created on the month that is being shown, and they are only created if:
- A championship exists on that month (it is possible to create a championship on the same flow) and;
- the championship of the that month does not have a final registered to it.

And that's basically it!

I hope you guys like it and sorry for the branch name, I ended up changing the implementation that I had planned when I named the branch :stuck_out_tongue_closed_eyes:

2018-01-22 11:45 UTC, cristiadu requested changes
small changes, other than that LGTM

2018-01-22 11:45 UTC, cristiadu commented on webapp/src/app/championship.service.ts
> +		delete championship._id;
Is this really necessary? Can you explain the reasoning behind this line change?

2018-01-22 11:45 UTC, cristiadu commented on webapp/src/app/championship.service.ts
> +		this.currentChampionship = championship;
@aquintiliano cmon man, wtf these typos. :P

2018-01-22 11:45 UTC, cristiadu commented on webapp/src/app/navigation-bar/navigation-bar.component.ts
> +			if (!window.confirm("Este mês ainda não tem um campeonato criado. Deseja criar?")) {
I know you will hate me for this, but... can you use confirmation modals instead of alerts? You know as a FE Developer that alerts are barely used right now and characterize a "bad practice"

2018-01-22 12:13 UTC, kiosia commented on webapp/src/app/championship.service.ts
> +		delete championship._id;
the update on mongo was failing because it was trying to update the id

i don't know why it started failing all of a sudden though

2018-01-22 12:13 UTC, kiosia commented on webapp/src/app/navigation-bar/navigation-bar.component.ts
> +			if (!window.confirm("Este mês ainda não tem um campeonato criado. Deseja criar?")) {
agreed! will do.

2018-01-23 00:16 UTC, kiosia commented on webapp/src/app/navigation-bar/navigation-bar.component.ts
> +			if (!window.confirm("Este mês ainda não tem um campeonato criado. Deseja criar?")) {
I AM NOT A FE DEV, IT'S NOT TRUE, IT'S BULLSHIT, I AM NOT A FE DEV, I AM NOT. oh hai chris.(please read this as tommy wiseau in this video: https://www.youtube.com/watch?v=M5PuJGzbcvY)

2018-01-23 00:47 UTC, kiosia commented on webapp/src/app/navigation-bar/navigation-bar.component.ts
> +			if (!window.confirm("Este mês ainda não tem um campeonato criado. Deseja criar?")) {
I'm opening a new issue for this since it is out of the scope of this feature. deal with it \o

2018-01-23 00:47 UTC, kiosia commented on webapp/src/app/navigation-bar/navigation-bar.component.ts
> +			if (!window.confirm("Este mês ainda não tem um campeonato criado. Deseja criar?")) {
https://github.com/aquintiliano/fifa-champs/issues/112

2018-01-23 14:32 UTC, cristiadu approved these changes

2018-01-23 14:32 UTC, merged