Fix requests of webapp
aquintiliano/fifa-champs pull request #120
Opened 2018-01-25 22:00 UTC by alandoni

2018-01-26 11:19 UTC, kiosia requested changes

2018-01-26 11:19 UTC, kiosia commented on api/server.js
> +//routes.set(app, mongo);
nope.avi

2018-01-26 11:19 UTC, kiosia commented on api/server.js
> +//const mongo = new MongooseController(databaseAddress);
nope.avi

2018-01-26 12:55 UTC, cristiadu commented on api/server.js
> +//const mongo = new MongooseController(databaseAddress);
nope.wmv

2018-01-26 12:55 UTC, cristiadu commented on api/server.js
> +//routes.set(app, mongo);
nope-alandoni-cut.wmv

2018-02-01 14:53 UTC, kiosia approved these changes
lgtm

2018-02-01 21:53 UTC, merged